name: build-windows
on:
  push: { branches: [ "main" ] }
  pull_request:
jobs:
  build-msys2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-glfw
      - name: Build
        shell: msys2 {0}
        run: gfortran forge.f90 -o forge.exe -lglfw3 -lopengl32 -lgdi32 -luser32 -lkernel32
      - uses: actions/upload-artifact@v4
        with:
          name: forge-windows-x64
          path: forge.exe
